### ISSUE TITLE
Canvas Integration: Serve HTML/JS/CSS from within the plugin

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/open-edx-plugins#13]
**Related to:**
https://github.com/mitodl/open-edx-plugins/issues/7#issuecomment-956173887 & https://github.com/mitodl/open-edx-plugins/issues/7#issuecomment-956292339

**Description:**
We have majorly migrated the canvas integration code from platform to plugin in https://github.com/mitodl/open-edx-plugins/pull/8. Since the instructor dashboard doesn't currently support as mentioned [here](https://github.com/mitodl/open-edx-plugins/pull/8). As a next step, we need to give a try to https://github.com/edx/web-fragments and see if we could pass through the html/js/css from within the plugin using the fragments(https://github.com/edx/web-fragments) and plugin contexts (https://github.com/edx/edx-django-utils/blob/master/edx_django_utils/plugins/README.rst).

**Experimantal Progress**
On the way of doing some experimental work we were able to migrate [some part](https://github.com/mitodl/edx-platform/commit/b61152ac70#diff-0d1ee66fb84bee6c3517980a7cefd74a050ccb60da9c0c3b662ab0a2d80d17c0R691) of the instructor dashboard from platform to the plugin and created [this branch in platform](https://github.com/mitodl/edx-platform/tree/arslan/canvas-context) and [this branch in open-edx-plugins](https://github.com/mitodl/open-edx-plugins/tree/arslan/canvas-plugin-context)

**Comment by pdpinch** [comment]
@arslanashraf7 is there anything left to do on this issue?

**Comment by arslanashraf7** [comment]
This is complete. Thanks for checking back on this.
