### ISSUE TITLE
Enable tests for all the open edX plugins

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/open-edx-plugins#212]
# Description/Context

The current configuration of pants and the plugins itself doesn't run the tests mostly (Python/Django tests). It is known that there aren't a lot of tests in the newly created plugins. But, For the plugins that were migrated from other repos to this mono repo, some of them had tests in their prior repositories.

No tests are being run at the time of writing this ticket. The only thing that runs is pre-commit.

## Examples of migrated plugins include:
- [edx_sysadmin](https://github.com/mitodl/open-edx-plugins/tree/main/src/edx_sysadmin)
- [ol_openedx_canvas_integration](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_canvas_integration)
- [ol_openedx_git_auto_export](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_git_auto_export)
- [ol_openedx_rapid_response_reports](https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_rapid_response_reports)

It is highly possible that these migrated plugins had tests at least [edx-sysadmin](https://github.com/mitodl/open-edx-plugins/tree/main/src/edx_sysadmin) does but we should check for the others. If there were tests for other plugins in their prior repositories/commits we should bring them in.

# Plan/Design
- Check the migrated plugins for existing plugins and bring them here in their new sub directories
- Enable pants to run tests (Possibility?) but we don't need to add them to bundle
- Add Github actions to run the tests throughout all the apps in this mono repo.

**Comment by pdpinch** [comment]
This seems quite important to me. 

Is it possible to set things up so we can target specific edx-platform distributions for testing? At the moment, we would have need for tests with Olive, Palm, Quince and master -- although not all our plugins are used in all those environments.

**Comment by arslanashraf7** [comment]
> Is it possible to set things up so we can target specific edx-platform distributions for testing? At the moment, we would have need for tests with Olive, Palm, Quince and master -- although not all our plugins are used in all those environments.

I believe Yes. We can use matrix GitHub Actions in a way that can run tests on all these releases with each commit or PR etc. But running these tests against these many releases would need setting them up in the GitHub Actions and running tests against them. Also, It would drastically increase the action completion time on any PR.
