### ISSUE TITLE
Create a plugin that maps SKUs to course ids...

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-edx-plugins#28]
and returns course ids in ecommerce URLs instead of SKUs. 

see this discussion: https://github.com/mitodl/mitxonline/issues/340#issuecomment-1035214336

### some research questions to start:  

- [ ] How are SKU's set normally on open edX?
- [ ] Assuming that's there's a table SKUs, should the plugin create a SKU every time a course is created?
- [ ] Or should we override an existing API so that the course id is returned instead of looking up the SKU?

**Comment by arslanashraf7** [comment]
Update:

The initial details regarding SKU question in the ticket description are:

>How are SKU's set normally on open edX?

The SKU is simply a `Char` field in the `CourseMode` table and is not really referred to as a relation to some other table [Model Reference](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/named-release-cypress/running_course/manage_course_fees.html#add-course-mode).

_This leads to a non-plugin solution as well_, Which means we can set our `Product_Id` from the MITxOnline as a value for the SKU field to the relevant course mode in the Open edX. And based on [this comment](https://github.com/mitodl/mitxonline/issues/340#issuecomment-1033683766). When a URL like `https://<marketing_site_base>/checkout/?sku=8CF08E5` is hit, we know that the SKU here is actually the productId from our marketing site. But this will require us to map the product within then edx while adding CourseMode entries.

> Assuming that's there's a table SKUs, should the plugin create a SKU every time a course is created?

SKUs are not part of an independent table they are part of [CourseModes table](https://github.com/openedx/edx-platform/blob/open-release/maple.master/common/djangoapps/course_modes/models.py#L42). As for how they are being set is related to how we generally set the price. It looks like they are added manually while adding a Course Mode through django admin. [Documentation](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/named-release-cypress/running_course/manage_course_fees.html#add-course-mode)

But I also like @rhysyngsun 's approach as well wherein the plugin will generate a URL for the marketing site with added course id. e.g. On the redirect from plugin, the generated URL will take the user to something like `https://<marketing_site_base>/checkout/?course_id=course-v1-...`. 
And in the marketing site, we decide to fetch the product id relevant to course_id and perform checkout stuff.

@rhysyngsun Is my above understanding correct?

FYI,  @pdpinch

**Comment by rhysyngsun** [comment]
@arslanashraf7 that sounds right, I think we want to avoid the first option since it adds additional complexity to mitx online

**Comment by arslanashraf7** [comment]
Yes, we can close this.
