### ISSUE TITLE
fix type checking issues

### ISSUE THREAD

**Issue by umarmughal824** [mitodl/open-edx-plugins#48]
- fix mypy error in pre-commit build

https://results.pre-commit.ci/run/github/402849512/1649939778.5AMOicBHTcivfgIBKbLmhQ

**Comment by arslanashraf7** [comment]
I think we can close this based on https://github.com/mitodl/open-edx-plugins/pull/36#discussion_r861643065 and the related changes in your PR. @umarmughal824
