### ISSUE TITLE
Identify pluggable & un-pluggable parts of the canvas integration

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/open-edx-plugins#7]
Subtask of #3 

In this ticket, we aim to identify what parts of the canvas integration can be moved into a pluggable Django app and what parts should be added in a branch inside of https://github.com/mitodl/edx-platform.

**Comment by arslanashraf7** [comment]
Update:

@pdpinch 
Generally, We have a couple of options to go forward with the pluggable app:

1. If we divide the parts into the pluggable app & edx-platform we can move all the `canvas_integration` app parts from [this commit](https://github.com/mitodl/edx-platform/commit/b61152ac70) into the pluggable and the remaining part would be pushed to `mitx branch` of our fork. (In this case, the functionality/UX would remain intact as it was earlier)
2. (**Depending on how useful this plugin would be for the community?**) If we decide to follow the edX's IDA practices then we should move all of the related plugin code into the plugin itself and we can only do that in 2 cases since we don't currently have an option to extend edX's instructor dashboard app with a plugin(This will require way more effort than point#1):
    - We convert this into an app like [edx-sysadmin](https://github.com/mitodl/edx-sysadmin) where we introduced a new URL(`<EDX_PLATFORM>/sysadmin`) for the whole plugin to work upon(In this case the canvas would no more be a part of the `Instructor` tab inside LMS/Course).
    - We try and convert it into a [Course Tab](https://openedx.atlassian.net/wiki/spaces/AC/pages/30965919/Adding+a+new+course+tab) in which case it will be moved up a step and the tab would be shown parallel to the `Instructor` tab in LMS (This seems feasible but it might require more R&D).

@pdpinch Which of the approaches above seem feasible to you?

**Comment by pdpinch** [comment]
Thank you for the research Arslan. We need to have this work with maple and released to Residential MITx by late December, so I think #1 is our only choice for now.

However, if we maintain a commit in our fork, we will be asking ourselves this same question again in 6 months with the nutmeg release. In the long term, we need to prepare for choice #2 as well. I can start engaging with the wider community on the issue, and try to determine which of the options seems more likely -- an extensible instructor dashboard, or leveraging the course tab. Perhaps @ziafazal has some thoughts.

**Comment by ziafazal** [comment]
@pdpinch @arslanashraf7 it appears edX has been converting [instructor dashboard to MFE](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1544945728/BD-12+Instructor+Dashboard+MFE+Conversion) and I'm not sure how much support MFEs has for plugins. edX does not provide support to extend instructor dashboard via plugins however, I think that support can be added following same pattern as [learner dashboard](https://github.com/edx/edx-platform/blob/99ceec86475251e76ac17b8b84c208e0f827864b/common/djangoapps/student/views/dashboard.py#L822) which seems very straight forward.
So I'd suggest to add that ability in instructor dashboard and move everything we have in canvas integration into separate plugin.

**Comment by arslanashraf7** [comment]
Update:

I'm posting an update here based on the above conversation.

As mentioned [here](https://github.com/mitodl/open-edx-plugins/issues/7#issuecomment-956292339), There are 2 PRs respectively in platform(https://github.com/mitodl/edx-platform/pull/274) & open-edx-plugins(https://github.com/mitodl/open-edx-plugins/pull/8) which collectively implement [point#1] completely (https://github.com/mitodl/open-edx-plugins/issues/7#issuecomment-956173887) as mentioned above. ✅ 

Moving onwards[point#1](https://github.com/mitodl/open-edx-plugins/issues/7#issuecomment-956173887), [comment](https://github.com/mitodl/open-edx-plugins/issues/7#issuecomment-956292339):
I've created 2 experimental branches([platform branch](https://github.com/mitodl/edx-platform/tree/arslan/canvas-context) & [plugin branch](https://github.com/mitodl/open-edx-plugins/tree/arslan/canvas-plugin-context)) to circle back to in future.

To keep track of future updates I've also created some tickets (https://github.com/mitodl/open-edx-plugins/issues/13, https://github.com/mitodl/open-edx-plugins/issues/10, https://github.com/mitodl/open-edx-plugins/issues/11, https://github.com/mitodl/open-edx-plugins/issues/12).

**Comment by arslanashraf7** [comment]
Closed as part of https://github.com/mitodl/open-edx-plugins/issues/3
