### ISSUE TITLE
refactor "download reports from instructor dashboard" as a pluggable app

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-edx-plugins#9]
In order to address mitodl/rapid-response-xblock#71 we patched edx-platform, but we should have implemented it as part of this XBlock, as an instructor dashboard plugin. 

### list of commits in edx-platform that should be factored out
- [ ] https://github.com/mitodl/edx-platform/pull/120/commits/f909d90683cea1a132022cc5e84b09521dfa53e7
- [ ] https://github.com/mitodl/edx-platform/pull/108/commits/1be9ffdf048865bc336a6b18fd6cb417a4b0ce02

**Comment by arslanashraf7** [comment]
Closed via https://github.com/mitodl/open-edx-plugins/pull/17 & https://github.com/mitodl/edx-platform/pull/275
